version: '3.3'

services:
  mywebsite-postgres:
    container_name: mywebsite-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPASSWORD: admin
    build:
      context: ./services/db
    ports:
      - '5432:5432'
    networks:
      - 'backend-net'

  mywebsite-api:
    container_name: mywebsite-api
    build:
      context: ./services/api
    ports:
      - '9001:9001'
    volumes:
      - './services/api:/src/api'
      - '/src/api/node_modules'
    environment:
      NODE_ENV: 'dev'
      port: '9001'
      BABEL_DISABLE_CACHE: 1
      JWT_SECRET: 'H34e626&D7'
      JWT_COOKIE_NAME: 'mywebsite-token'
      DATABASE_URL: 'postgres://admin:admin@mywebsite-postgres:5432/mywebsite'
      DATABASE_TEST_URL: 'postgres://admin:admin@mywebsite-postgres:5432/mywebsite-integration'
    networks:
      - 'backend-net'
      - 'frontend-net'

  mywebsite-web:
    container_name: mywebsite-web
    build:
      context: ./client
    ports:
      - '3000:3000'
      - '35729:35729'
    environment:
      NODE_ENV: 'development'
      CHOKIDAR_USEPOLLING: 1
      JWT_SECRET: 'H34e626&D7'
      JWT_COOKIE_NAME: 'mywebsite-token'
    volumes:
      - './client:/src/app'
      - '/src/app/node_modules'
    depends_on:
      - 'mywebsite-postgres'
      - 'mywebsite-api'
    networks:
      - 'frontend-net'

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
